version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    timezone: Africa/Cairo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python-telegram-bot
    versions:
    - "13.3"
